apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-app
        image: flask-app-test:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-entry
  namespace: default
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

